version: '3.4'

services:
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER : "postgres"
            POSTGRES_PASSWORD : "password"
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "password"