# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build

on:
  push:
    branches: ["main", "version/**/*", "dev/**/*"]
  pull_request:
    branches: ["version/**/*"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore 
      run: dotnet restore ./src/NanoWorks.sln
    - name: Build
      run: dotnet build ./src/NanoWorks.sln --no-restore
    - name: Test
      run: dotnet test ./src/NanoWorks.sln --no-build --verbosity normal --filter FullyQualifiedName!~IntegrationTests
