# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build, Pack, Push Version

on:
  push:
    branches: ["version/**/*"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore 
      run: dotnet restore ./src/NanoWorks.sln

    - name: Build
      run: dotnet build ./src/NanoWorks.sln --no-restore

    - name: Test
      run: dotnet test ./src/NanoWorks.sln --no-build --verbosity normal --filter FullyQualifiedName!~IntegrationTests

    - name: Pack NanoWorks.Cache
      run: dotnet pack ./src/Cache/NanoWorks.Cache/NanoWorks.Cache.csproj -p:PackageVersion=${{ vars.PACKAGE_VERSION }} --output ./pack

    - name: Pack NanoWorks.Cache.Redis
      run: dotnet pack ./src/Cache/NanoWorks.Cache.Redis/NanoWorks.Cache.Redis.csproj -p:PackageVersion=${{ vars.PACKAGE_VERSION }}--output ./pack

    - name: Push
      run: dotnet nuget push ./pack/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
