# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Cache Build, Pack, Push Prerelease

on:
  push:
    branches: ["version/**/*"]
    paths: ["src/Cache/**"]

jobs:
  build-pack-push:

    runs-on: ubuntu-latest

    env:
      PACKAGE_VERSION: ${{vars.PRERELEASE_PACKAGE_VERSION}}-${{github.run_id}}
      NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore 
      run: dotnet restore ./src/NanoWorks.sln

    - name: Build
      run: dotnet build ./src/NanoWorks.sln --no-restore

    - name: Test
      run: dotnet test ./src/NanoWorks.sln --no-build --verbosity normal --filter FullyQualifiedName!~IntegrationTests

    - name: Pack NanoWorks.Cache
      run: dotnet pack ./src/Cache/NanoWorks.Cache/NanoWorks.Cache.csproj -p:PackageVersion=$PACKAGE_VERSION --output ./pack

    - name: Pack NanoWorks.Cache.Redis
      run: dotnet pack ./src/Cache/NanoWorks.Cache.Redis/NanoWorks.Cache.Redis.csproj -p:PackageVersion=$PACKAGE_VERSION --output ./pack

    - name: Push
      run: dotnet nuget push ./pack/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
